### ISSUE TITLE
[BUG]: Existing chat disappears when a new chat is started

### ISSUE THREAD

**Issue by ssling0817** [NVIDIA/NeMo-Agent-Toolkit#467]
### Version

aiq, version 0.1.dev117+ge0b7f4a.d20250710

### Describe the bug.

When I have an existing chat open and start a new chat, the existing chat disappears as soon as I get the first response in the new chat. This behavior is consistent and happens every time.

### Minimum reproducible example

```shell
Open an existing chat session

Start a new chat (e.g., by typing a new prompt)

Observe that the previous chat disappears once the new chat receives its first response
```

### Code of Conduct

- [x] I agree to follow the AIQ toolkit Code of Conduct
- [x] I have searched the [open bugs](https://github.com/NVIDIA/NeMo-Agent-Toolkit/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by ericevans-nv** [comment]
This issue has been resolved in aiq version 1.2.0.dev115+g75d8fbff.d20250722. Please update your installation and verify that it works as expected.

**Comment by ssling0817** [comment]
@ericevans-nv Could you point out which commit or PR solve this issue? Thanks.

**Comment by ssling0817** [comment]
@ericevans-nv I merge the latest update and use `git submodule update --init --recursive` to update the UI but the error is still there. I type` aiq --version,` and it still showed `aiq, version 0.1.dev117+ge0b7f4a.d20250710`, but I did merge the latest code.

**Comment by ssling0817** [comment]
@ericevans-nv I just clone the latest code from https://github.com/NVIDIA/NeMo-Agent-Toolkit-UI.git, and the error is still there. Is it not happening from your side?

**Comment by ericevans-nv** [comment]
I'm not seeing the same behavior on my end. Could you provide more details, such as an example, steps to reproduce, or any relevant screenshots so I can help investigate further?
